services:
  web:
    build:
      context: ./Serverside/
      dockerfile: докерфайл
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=sexdb;User Id=bebrik;Password=bebriksecret;
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bebrik
      POSTGRES_PASSWORD: bebriksecret
      POSTGRES_DB: sexdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:    
      - "1489:80"
    depends_on:
      - db

volumes:
  postgres_data:

